apiVersion: v1
kind: Service
metadata:
  name: flask-app-service
  namespace: flask
spec:
  selector:
    app: flask-app
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090
      nodePort: 30090
  type: NodePort
